### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by zhouyangyu** [gabrieltempass/streamlit-theme#1]
First of all, I'm so glad you have a plug-in for this! Thank you!

```
from streamlit_theme import st_theme

if st_theme()['base'] == 'dark':
    st.image('logo-white-text.png')
else:
    st.image('logo-dark-text.png')
```

After starting the streamlit server, I get the following error for a brief second (and it shows red box on the streamlit app), before disappearing and the code above works as expected.
```
...
    if st_theme()['base'] == 'dark':
TypeError: 'NoneType' object is not subscriptable
```

That brief second of error is really annoying and I want the users to have a smooth experience. Any ideas how I can avoid the temporary error?  Thanks!

**Comment by gabrieltempass** [comment]
Hi @zhouyangyu!
Thanks, I'm happy that you liked the component!

You are getting this error because you can't get `['base']` from a `None` object. The `st_theme()` function returns a dictionary or `None`. When you start the Streamlit server, for a brief second `st_theme()` returns `None`. Then, when the page is properly loaded, it returns the theme dictionary.

So to correct the error you simply need to take this possible return value into account in the condition of your code. For example:

```python
if st_theme() is None or st_theme()['base'] == 'dark':
    st.image('logo-white-text.png')
else:
    st.image('logo-dark-text.png')
```
